import { useState } from 'react'
import { ColumnDef, flexRender, getCoreRowModel, useReactTable } from '@tanstack/react-table'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import type { NextPage } from 'next'

type Person = {
  firstName: string
  lastName: string
  age: number
  visits: number
  status: string
  progress: number
}

const defaultData: Person[] = [
  {
    firstName: 'tanner',
    lastName: 'linsley',
    age: 24,
    visits: 100,
    status: 'In Relationship',
    progress: 50,
  },
  {
    firstName: 'tandy',
    lastName: 'miller',
    age: 40,
    visits: 40,
    status: 'Single',
    progress: 80,
  },
  {
    firstName: 'joe',
    lastName: 'dirte',
    age: 45,
    visits: 20,
    status: 'Complicated',
    progress: 10,
  },
]

const columns: ColumnDef<Person>[] = [
  // {
  //   header: 'Name',
  //   columns: [
  //     {
  //       accessorKey: 'firstName',
  //       cell: info => info.getValue(),
  //     },
  //     {
  //       accessorFn: row => row.lastName,
  //       id: 'lastName',
  //       cell: info => info.getValue(),
  //       header: () => <span>Last Name</span>,
  //     },
  //   ],
  // },
  {
    header: 'firstName',
    accessorKey: 'firstName'
  },
  {
    header: 'lastName',
    accessorKey: 'lastName'
  },
  // {
  //   header: 'Info',
  //   columns: [
  //     {
  //       accessorKey: 'age',
  //       header: () => 'Age',
  //     },
  //     {
  //       header: 'More Info',
  //       columns: [
  //         {
  //           accessorKey: 'visits',
  //           header: () => <span>Visits</span>,
  //         },
  //         {
  //           accessorKey: 'status',
  //           header: 'Status',
  //         },
  //         {
  //           accessorKey: 'progress',
  //           header: 'Profile Progress',
  //         },
  //       ],
  //     },
  //   ],
  // },
  {
    header: 'Age',
    accessorKey: 'age'
  },
  {
    header: 'Visits',
    accessorKey: 'visits'
  },
  {
    header: 'Status',
    accessorKey: 'status'
  },
  {
    header: () => <span>Profile Progress</span>,
    accessorKey: 'progress'
  }
]

const Home: NextPage = () => {
  const [data, setData] = useState(() => [...defaultData]);

  const table = useReactTable({
    data: data,
    columns: columns,
    getCoreRowModel: getCoreRowModel()
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!+TypeScript</a><br /> with TanStack Table
        </h1>
        <table>
          <thead>
            {table.getHeaderGroups().map(headers => (
              <tr key={headers.id}>
                {headers.headers.map(header => (
                  <th key={header.id} className={styles.th}>
                    {header.isPlaceholder
                    ? null
                    : flexRender(
                        header.column.columnDef.header,
                        header.getContext()
                      )}
                  </th>
                ))}
              </tr>
            ))}
          </thead>
          <tbody>
            {table.getRowModel().rows.map(row => (
              <tr key={row.id}>
                {row.getVisibleCells().map(cell => (
                  <td key={cell.id} className={styles.td}>
                    {flexRender(cell.column.columnDef.cell, cell.getContext())}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </main>
    </div>
  )
}

export default Home
